name: rethinkdb_dart
version: 2.3.2+6
authors:
  - Rowan Dash <rowandash@outlook.com>
  - William Welch <billywelch@gmail.com>
  - Marcelo Henrique Neppel <marcelo.neppel@gmail.com>
description: Dart 2 driver for RethinkDB v2.3.
homepage: https://github.com/marceloneppel/rethinkdb
documentation: https://github.com/marceloneppel/rethinkdb
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  protobuf: ^0.13.15
  crypto: ^3.0.1
  convert: ^3.0.0
  pbkdf2ns: ^0.0.2
dev_dependencies:
  test: ^1.6.5
  pedantic: ^1.8.0
